M48
; DRILL file {KiCad 7.0.10} date Sun Dec 22 17:19:56 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-12-22T17:19:56-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0453
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0689
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.0787
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T5C0.0984
%
G90
G05
T1
X3.048Y-4.2997
T2
X3.048Y-3.5123
T3
X5.6683Y-3.3301
X5.6683Y-4.0317
T4
X5.1628Y-4.5224
X5.7644Y-4.5224
T5
X2.564Y-2.564
X2.566Y-4.4929
X4.8494Y-2.5638
X4.8494Y-4.4929
M30
