M48
; DRILL file {KiCad 8.0.4} date 2025-03-23T22:29:43-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-03-23T22:29:43-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.160
%
G90
G05
T1
X2.44Y-4.47
X8.44Y-4.47
T2
X51.073Y-3.894
X51.073Y-24.724
M30
