(part "AISC-1210HS-180K-T2"
    (packageRef "AISC-1210HS")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "171")
    (property "Mouser_Part_Number" "815-AISC1210HS180KT2")
    (property "Mouser_Price/Stock" "https://www.mouser.com/Search/ProductDetail.aspx?qs=bWAYEm3xoCYdK%252b9sqxmckg%3d%3d")
    (property "Manufacturer_Name" "ABRACON")
    (property "Manufacturer_Part_Number" "AISC-1210HS-180K-T2")
    (property "Description" "Inductor RF Molded Wirewound 39uH 10% 2.52MHz 30Q-Factor 0.065A 6.4Ohm DCR 1210 T/R")
    (property "Datasheet_Link" "https://componentsearchengine.com/Datasheets/1/AISC-1210HS-180K-T2.pdf")
    (property "symbolName1" "AISC-1210HS-180K-T2")
)
