M48
; DRILL file {KiCad 7.0.10} date Saturday, February 24, 2024 at 05:00:35 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-02-24T17:00:35-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X147.81Y-98.31
X147.87Y-121.36
X205.84Y-98.31
X205.84Y-121.3
M30
