M48
; DRILL file {KiCad 7.0.10} date Sun Dec 22 23:47:15 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-12-22T23:47:15-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0472
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0850
%
G90
G05
T1
X0.0961Y-0.176
X0.3323Y-0.176
T2
X2.0107Y-0.1533
X2.0107Y-0.9734
M30
