M48
; DRILL file {KiCad 7.0.8} date 2024 August 03, Saturday 17:37:34
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-08-03T17:37:34-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0827
%
G90
G05
T1
X3.3453Y-5.5815
X3.3744Y-3.8406
X5.6992Y-3.865
X5.7232Y-5.5815
T0
M30
