(part "TPS7150QDR"
    (packageRef "SOIC127P600X175-8N")
    (interface
        (port "1" (symbPinId 1) (portName "GND") (portType INOUT))
        (port "2" (symbPinId 2) (portName "%EN%") (portType INOUT))
        (port "3" (symbPinId 3) (portName "IN_1") (portType INOUT))
        (port "4" (symbPinId 4) (portName "IN_2") (portType INOUT))
        (port "5" (symbPinId 5) (portName "OUT_1") (portType INOUT))
        (port "6" (symbPinId 6) (portName "OUT_2") (portType INOUT))
        (port "7" (symbPinId 7) (portName "SENSE†") (portType INOUT))
        (port "8" (symbPinId 8) (portName "PG") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "595-TPS7150QDR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/TPS7150QDR?qs=Gse6rAGbi79xIQtuYfAffQ%3D%3D")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "TPS7150QDR")
    (property "Description" "LDO Voltage Regulators Lowest Dropout PMOS")
    (property "Datasheet_Link" "https://www.ti.com/lit/gpn/TPS71")
    (property "symbolName1" "TPS7150QDR")
)
