name: Restrict Subfolder Access

on: [push]

jobs:
  restrict_subfolders:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2  # Fetch at least two commits for diff

      - name: Check changed files
        run: |
          # Get the list of files changed in the push
          files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} || echo "")

          # Define user-subfolder mapping
          declare -A user_folders=(
	    ["justiin-wang"]="\21xt\03-wireless_strain_gauge\"
            ["aarenclwong"]="\21xt\02-mainbox\"
          )

          # Get the GitHub username of the pusher
          pusher=${{ github.actor }}

          # Get the subfolder the user is allowed to modify
          allowed_folder=${user_folders[$pusher]}

          # Check if the changed files are within the allowed folder
          for file in $files; do
            if [[ ! $file == $allowed_folder/* ]]; then
              echo "Error: $pusher is not allowed to modify $file"
              exit 1
            fi
          done

          echo "All changes are within the allowed folder"
